### ISSUE TITLE
Please add yola as an owner to package in pypi

### ISSUE THREAD

**Issue by thomasw** [yola/djstopie#9]
@imorrison, I'm assuming that you don't want to maintain this. Could you add the yola user as an owner to the package in pypi?

The form is here: https://pypi.python.org/pypi?:action=role_form&package_name=djstopie

**Comment by imorrison** [comment]
I added the username 'yola' as an owner. See if that works for you.

**Comment by thomasw** [comment]
It did. Thanks, @imorrison. 👍
